public enum EnumGameScene
{
    INTRODUCTION,
    INSTRUCTION,
    APRESENTATION_LEVEL01,
    LEVEL01,
    APRESENTATION_LEVEL02,
    LEVEL02,
    APRESENTATION_LEVEL03,
    LEVEL03,
    APRESENTATION_LEVEL04,
    LEVEL04,
    GAMEOVER,
    WINNER,
    RECORDREGISTER,
    HIGHRESCORED
};